resolver: lts-17.5

packages:
  - .

allow-newer: true
extra-deps:
  - streaming-postgresql-simple-0.2.0.5
  - opaleye-0.6.7003.1
    # This is not the latest opaleye
    # Not necessarily even the latest one that works
    # Try increasing me

