resolver: lts-10.8

packages:
  - location:
      git: http://github.com/tomjaguarpaw/haskell-opaleye
      commit: master
    extra-dep: true
  - .

extra-deps:
    - streaming-postgresql-simple-0.2.0.3
